---
title: "DivideFunction"
format: html
---

The DivideFunction is a utility function that divides the value of its first child (the numerator) by the product of its subsequent children (the denominators).

## Overview

The DivideFunction divides the value of the first child function by the product of all subsequent child functions (i.e. It starts from the first child function, recursively divide by the values of the subsequent child functions). If the numerator is zero, the function returns zero. If any denominator is zero, the function returns positive or negative infinity depending on the sign of the numerator. This is useful for safely performing division operations in plant growth models, such as calculating ratios or efficiencies, while handling division-by-zero scenarios.

## Model Structure

{{< include /_includes/Models/model-structure-intro.md >}}

* [Model](/docs/Models/Core/Model.qmd)
* [IFunction](/docs/APSIM.Core/IFunction.qmd)
* [IStructureDependency](/docs/APSIM.Core/IStructureDependency.qmd)

## Connections to Other Components

{{< include /_includes/Models/connections-intro.md >}}

| Component | Connection Type | Description |
|-----------|-----------------|-------------|
| Child Functions | [IFunction](/docs/APSIM.Core/IFunction.qmd) | All child functions are used in the division operation; the first child is the numerator, and subsequent children are denominators. |

## Model Variables

{{< include /_includes/Models/model-variables-intro.md >}}

**Configurable and Reportable Properties**

> No configurable properties are available for this function.

**Read-Only Reportable Properties**

| Property             | Type    | Description                                                                 |
|----------------------|---------|-----------------------------------------------------------------------------|
| Value   | double  | The sum of values from all child functions.                      |

## Processes and Algorithms

{{< include /_includes/Models/processes-intro.md >}}

### Division Algorithm

The DivideFunction implements a sequential division algorithm with special handling for edge cases:


Starting with the first child function as the numerator, the algorithm recursively divides by each subsequent child function:


## User Interface

DivideFunction can be added into the model tree by right-clicking on a parent node and selecting "Add Model...", then searching for DivideFunction in the Filter Box. A symbol for the DivideFunction is displayed in the user interface to represent the function.


## Practical Example

Suppose you want to calculate the water use efficiency (WUE) of a crop, which is the ratio of yield to water used:

$$
WUE = \frac{Yield}{WaterUsed}
$$

The DivideFunction can be used to divide the Yield by WaterUsed. If WaterUsed is zero, the function will return positive infinity to indicate an undefined or infinite result.

## See Also

* **Source code:** [DivideFunction.cs on GitHub](http://github.com/APSIMInitiative/ApsimX/blob/master/Models/Functions/DivideFunction.cs)