---
title: "GrainFilling"
format: html
---


The **GrainFilling** phase in [Wheat](/docs/Plants/Wheat) represents the developmental period from **MaximumGrainLength** to **EndGrainFill**. It is influenced by thermal time only.

## Overview

The [GenericPhase](/docs/Models/PMF/Phenology/Phases/GenericPhase.qmd) model simulates the time between the `MaximumGrainLength` and `EndGrainFill` stages.

- This phase starts at **MaximumGrainLength** and ends at **EndGrainFill**, when the grain is considered to be fully ripe.
- The model uses daily [Thermal Time](ThermalTime.qmd), retrieved from the `[Phenology].ThermalTime` function.
- The **Target thermal time** is fixed as constant for this phase, with default value of 545.0 °Cd.:


## Cultivar-Specific Parameters

| Name       | Description                                         | Default Value |
|------------|-----------------------------------------------------|---------------|
| [Phenology].GrainFilling.Target.FixedValue   | Thermal time target during grain filling (°Cd)      | 545.0          |

## Practical Example

> no practical example available
