---
title: "CAMP"
outertheme: "html_document"
---


Cereal Anthesis Molecular Phenology (CAMP) model [@brown_integration_2013] is based on the @kirby_analysis_1988's Framework which assumes the timing of anthesis is a result of the timing of flag leaf and an additional thermal time passage from there to heading then anthesis. It also assumes the timing of flag leaf is a result of the Final Leaf Number (which sets a target) and leaf appearance rate (which sets the rate of progress toward the target). Leaf appearance rate is a function of Thermal time and a cultivar specific Phyllochron which changes with Haun stage as described by [@jamieson_sirius:_1998].


Master model, **[CAMP](CAMP.qmd)**, is the main entry point for the Cereal Anthesis Molecular Phenology model in APSIM NG. Others are the submodels required by CAMP.

The table below lists the submodels that are required by CAMP:

| Title                   | Description                                                                                  |
|-------------------------|----------------------------------------------------------------------------------------------|
| [FinalLeafNumberSet](FinalLeafNumberSet.qmd)     | Store the final leaf number parameters estimated for a cultivar under controlled environments |
| [FLNParameterEnvironment](FLNParameterEnvironment.qmd) | Capture the controlled environment conditions to observe final leaf number |
| [CultivarRateParams](CultivarRateParams.qmd)     |  Stores vernalisation rate parameters for a specific cultivar  |
| [ColdVrnResponse](ColdVrnResponse.qmd)           |  Models the upregulation of the Vrn1 gene in response to cold temperatures |
| [CalcCAMPVrnRates](CalcCAMPVrnRates.qmd)         | Calculates vernalization expression for the given cultivar and environmental conditions |
