---
title: "SpikeletsDifferentiating"
output: html_document
---


The **SpikeletsDifferentiating** phase in [Wheat](/docs/Plants/Wheat) represents the developmental period from **DoubleRidge** to **MaximumSpikeletPrimordia**. It is influenced by vernalisation expression after double ridge.

## Overview

The [GenericPhase](/docs/Models/PMF/Phenology/Phases/GenericPhase.qmd) model simulates the time between the `DoubleRidge` and `MaximumSpikeletPrimordia` stages.

- This phase starts at **DoubleRidge** and ends at **MaximumSpikeletPrimordia**.
- The model uses daily changes of vernalisation expression ($\Delta Vrn$ in the [CAMP](/docs/Models/PMF/Phenology/CAMP/index.qmd)) to progress phase development.
- The **Target** is fixed as constant for this phase, with default value of 1 which means the total vernalisation expression is reached `2` to proceed into next phase.


## Cultivar-Specific Parameters

> no cultivar-specific parameters available

## Practical Example

> no practical example available

## Simulation Example

See the practical example in the [LeafInitiating](LeavesInitiating.qmd).
